name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  # check-for-cc:
  #  runs-on: nixos-latest
  #  steps:
  #    - name: check-for-cc
  #      id: check-for-cc
  #      uses: agenthunt/conventional-commit-checker-action@v2.0.1

  flake:
    runs-on: nixos-runner
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #main
      - name: Build
        run: |
            nix develop --command cargo test --workspace --all-targets --all-features
            nix develop --command cargo test --workspace --doc --all-features
            nix develop --command cargo build --all-targets
