name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  # check-for-cc:
  #  runs-on: nixos-latest
  #  steps:
  #    - name: check-for-cc
  #      id: check-for-cc
  #      uses: agenthunt/conventional-commit-checker-action@v2.0.1

  flake:
    runs-on: nixos-runner
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: nix develop --command cargo build
