name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  # check-for-cc:
  #  runs-on: nixos-latest
  #  steps:
  #    - name: check-for-cc
  #      id: check-for-cc
  #      uses: agenthunt/conventional-commit-checker-action@v2.0.1

  flake:
    runs-on: nixos-runner
    steps:
      - uses: actions/checkout@1cce3390c2bfda521930d01229c073c7ff920824 #main
      - name: Test and Build
        uses: philipcristiano/actions/nix-rust-test-and-build@535a1cda5d945641884694f662e4c4ae3f6aab8c # main
