name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  rust_release:
    runs-on: nixos-runner
    steps:

      - name: Checkout repository
        uses: actions/checkout@1cce3390c2bfda521930d01229c073c7ff920824 #main
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Set Git account
        run: |
          git config user.name "forgejo-actions[bot]"
          git config user.email "forgejo-actions[bot]@example.com"
          BARE_HOST="${FORGEJO_SERVER_URL#https://}"
          BARE_HOST="${BARE_HOST#http://}"
          git config --global url."https://forgejo-actions[bot]:${{ secrets.RELEASE_PLZ_TOKEN }}@${BARE_HOST}".insteadOf "${FORGEJO_SERVER_URL}"

      - name: Run release-plz
        uses: philipcristiano/release-plz-action@b36028081feace3f98562d02fc9752b13f38ef68 # main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          SQLX_OFFLINE: true
        with:
          VERBOSE: true

  flake:
    runs-on: nixos-runner
    steps:
      - uses: actions/checkout@1cce3390c2bfda521930d01229c073c7ff920824 # main
      - name: Test and Build
        uses: philipcristiano/actions/nix-rust-test-and-build@535a1cda5d945641884694f662e4c4ae3f6aab8c #main
