name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  rust_release:
    uses: "philipcristiano/workflows/.github/workflows/rust_release.yml@main"
    needs: [flake, rust]
    secrets:
      WF_GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  flake:
    runs-on: nixos-latest
    steps:
      - name: Install Node
        run: nix-env -iA nixpkgs.nodejs
      - uses: actions/checkout@v4
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: nix --experimental-features 'nix-command flakes' develop --command cargo build
